{% set name = "linkify-it-py" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/linkify-it-py-{{ version }}.tar.gz
  sha256: 68cda27e162e9215c17d786649d1da0021a451bdc436ef9e0fa0ba5234b9b048

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - uc-micro-py

test:
  imports:
    - linkify_it
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tsutsu3/linkify-it-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Links recognition library with FULL unicode support.

extra:
  recipe-maintainers:
    - thewchan
    - tsutsu3
    - chrisjsewell
