{% set name = "linkify-it-py" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19f3060727842c254c808e99d465c80c49d2c7306788140987a1a7a29b0d6ad2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - uc-micro-py >=1.0.1,<2.0.0

test:
  imports:
    - linkify_it

about:
  home: https://github.com/tsutsu3/linkify-it-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Links recognition library with FULL unicode support.

extra:
  recipe-maintainers:
    - tsutsu3
    - chrisjsewell
